In [3]:
import cv2
import numpy as np
import os
import glob
 
# Defining the dimensions of checkerboard
CHECKERBOARD = (6,9)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 
 

# defining world points
objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None
 


In [5]:
# Extracting path of individual image stored in a given directory
images = glob.glob('./Calibration_pictures/*.jpg')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
     
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
         
        imgpoints.append(corners2)
 
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
     
    cv2.imshow('img',img)
    cv2.waitKey(0)

cv2.destroyAllWindows()
 
h,w = img.shape[:2]
 
"""
Performing camera calibration by 
passing the value of known 3D points (objpoints)
and corresponding pixel coordinates of the 
detected corners (imgpoints)
"""
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
 
print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)

Camera matrix : 

[[3.08392660e+03 0.00000000e+00 1.98378736e+03]
 [0.00000000e+00 3.07897379e+03 1.49240126e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
dist : 

[[ 1.38991070e-01 -6.27088618e-01 -8.20952899e-04  1.78121938e-04
   7.51806657e-01]]
rvecs : 

(array([[ 0.03250604],
       [-0.04917548],
       [ 1.58310811]]), array([[0.32430171],
       [0.20347183],
       [1.55843014]]), array([[0.50862604],
       [0.35718196],
       [1.53422464]]), array([[-0.1203122 ],
       [-0.32858672],
       [ 1.53363162]]), array([[-0.37024367],
       [-0.54411988],
       [ 1.49340813]]), array([[ 0.24122406],
       [-0.28282813],
       [ 1.55885191]]), array([[ 0.3612009 ],
       [-0.38373537],
       [ 1.53571713]]), array([[ 0.68930594],
       [-0.18386573],
       [ 1.42248062]]), array([[ 0.21967744],
       [-0.71653839],
       [ 1.54660645]]), array([[-0.07786131],
       [ 0.16617241],
       [ 1.56866823]]), array([[-0.17998585],
       [ 0.24325408],
       [ 1.57

In [11]:
print(mtx)

[[3.08392660e+03 0.00000000e+00 1.98378736e+03]
 [0.00000000e+00 3.07897379e+03 1.49240126e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
